version: '3'

services:
  database:
    container_name: "PlannerPostgresDB"
    image: (замените на свое имя из docker hub)/postgres:2.0
    restart: always
    environment:
      POSTGRES_DB: planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: planner
      DATABASE_URL: jdbc:postgresql://PlannerPostgresDB:5432/planner
    ports:
      - "5433:5432"

  planner:
    image: ${DOCKER_TAG}
    container_name: "PlannerServ"
    depends_on:
      - database
    environment:
      DATABASE_URL: jdbc:postgresql://PlannerPostgresDB:5432/planner
      DATABASE_HOST: PlannerPostgresDB
      DATABASE_PORT: 5432
      DATABASE_NAME: planner
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: planner
    ports:
      - "8080:8080"
